### ISSUE TITLE
professionals

### ISSUE THREAD

**Issue by nyakiomaina** [MUGABA/team-220#4]
id - int primary key
email  - varchar(255) required
first_name - varchar(255) required
last_name - varchar(255) required
contact - varchar (30) required
residence - varchar(255) required
profession - varchar(255) required
password - text required

**Comment by MUGABA** [comment]
try to write in the do colomn of the second project of the link i shared

**Comment by MUGABA** [comment]
okay

**Comment by nyakiomaina** [comment]
what??

**Comment by MUGABA** [comment]
Try to go to create stories on the project not the issues tap click the projects tab the click the first project and create stories on the draft tab
